stages:
  - build
  - deploy

build:
  stage: build
  image: node:8
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build/


deploy:
  stage: deploy
  image: "ruby:2.5"
  script:
    # install dpl:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app=$HEROKU_DEV_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - dev
