image: node:8.10.0-alpine
cache:
  key: "alpine"
  paths:
    - node_modules/

stages:
  - build
  - staging
  - production

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build
  tags:
    - docker
  only:
    - dev

staging:
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd dist
    - dpl --provider=heroku --app=$HEROKU_DEV_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - dev

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd dist
    - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master
